version: '3.3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: email
      WATCHTOWER_NOTIFICATION_EMAIL_TO: 'email'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: posteo.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: 'email'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: 'password'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_REMOVE_VOLUMES: 'true'
      WATCHTOWER_INCLUDE_RESTARTING: 'true'
      WATCHTOWER_INCLUDE_STOPPED: 'true'
      WATCHTOWER_REVIVE_STOPPED: 'true'
      WATCHTOWER_NO_STARTUP_MESSAGE: 'false'
      WATCHTOWER_SCHEDULE: '0 0 3 * *'
